services:
  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=brenda123
      - AUTHENTICATION_MANAGER_EMAIL=admin@admin.com
      - AUTHENTICATION_MANAGER_PASSWORD=admin
      - CORS_ORIGIN=*
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=https://saikxbildeupefudrrhl.supabase.co/functions/v1/whatsapp-webhook
      - WEBHOOK_EVENTS_MESSAGE_UPSERT=true
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution@postgres:5432/evolution?sslmode=disable
      - DATABASE_SAVE_DATA_INSTANCE=true
    depends_on:
      - postgres
    volumes:
      - evolution_instances:/evolution/instances

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  evolution_instances:
  postgres_data:
